---
- name: Add Vagrant User to Admin Group
  command: usermod -aG adm vagrant

- name: Install Sandbox Packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - apache2
    - libapache2-mod-gnutls
    - php5
    - php5-dev
    - php5-cli
    - php5-curl
    - php5-intl
    - php5-gmp
    - php5-gd
    - php5-json
    - php5-imagick
    - php5-mcrypt
    - php5-mongo
    - php5-mysqlnd
    - php5-sqlite
    - php5-xmlrpc
    - php5-xsl
    - php-pear
    - ruby-sass
    - nodejs
    - python-nltk
    - python-sphinx
    - libpcre3-dev
    - libcv2.4
    - libcv-dev
    - build-essential
    - vim
    - git
    - memcached
    - libmemcached-dev
    - libmemcached10
    - libmemcache-dev
    - libmemcache0
    - tree

- name: Disable mod_ssl
  command: a2dismod ssl

- name: Activate Apache modules
  command: a2enmod rewrite deflate expires env headers setenvif gnutls

- name: Generate SnakeOil Certificates
  command: make-ssl-cert generate-default-snakeoil --force-overwrite

- name: Deactivate default vhost
  command: a2dissite 000-default.conf

- name: Copy Apache Default Server conf over
  copy: src=server dest=/etc/apache2/conf-available/server.conf

- name: Activate Server Conf
  command: a2enconf server.conf

- name: Set Apache Runtime Envvars
  lineinfile: dest=/etc/apache2/envvars regexp='(export APACHE_RUN_{{item}}=www-data|export APACHE_RUN_{{item}}=vagrant)' line='export APACHE_RUN_{{item}}=vagrant' state=present
  with_items:
  - USER
  - GROUP

- name: Copy sandbox site control
  copy: src={{item}} dest=/usr/local/bin/ owner=root mode=0755
  with_items:
  - attach-site
  - detach-site

- name: Set PHP timezone
  lineinfile: dest={{item}}.ini regexp='(;date.timezone =|date.timezone = "Europe/London")' line='date.timezone = "Europe/London"' state=present
  with_items:
  - /etc/php5/apache2/php
  - /etc/php5/cli/php

- name: Set PHP Display Errors
  lineinfile: dest={{item}}.ini regexp='(display_errors = Off|display_errors=On)' line='display_errors=On' state=present
  with_items:
  - /etc/php5/apache2/php
  - /etc/php5/cli/php

- name: Set PHP Error Reporting
  lineinfile: dest={{item}}.ini regexp='(error_reporting = E_ALL & ~E_DEPRECATED & ~E_STRICT|error_reporting=E_ALL)' line='error_reporting=E_ALL' state=present
  with_items:
  - /etc/php5/apache2/php
  - /etc/php5/cli/php

- name: Set PHP upload filesize
  lineinfile: dest={{item}}.ini regexp='(upload_max_filesize = 2M|upload_max_filesize = 10M)' line='upload_max_filesize = 10M' state=present
  with_items:
  - /etc/php5/apache2/php
  - /etc/php5/cli/php

- name: Set PHP post size
  lineinfile: dest={{item}}.ini regexp='(post_max_size = 8M|post_max_size = 12M)' line='post_max_size = 12M' state=present
  with_items:
  - /etc/php5/apache2/php
  - /etc/php5/cli/php

- name: Set Pear Config
  command: "{{item}}"
  with_items:
  - pear config-set preferred_state beta
  - pear config-set auto_discover 1
  ignore_errors: yes

- name: Add Pear Channels
  command: "pear channel-discover {{item}}"
  with_items:
  - pear.phpdoc.org
  - pear.phpunit.de
  - pear.phing.info
  ignore_errors: yes

- name: Install Pecl Components
  command: "pecl install {{item}}"
  with_items:
  - oauth
  - xdebug
  - memcached
  ignore_errors: yes

- name: "Install Memcache"
  action: shell printf "yes\n" | sudo pecl install memcache
  ignore_errors: yes

- name: Install Pear Components
  command: "pear install --alldeps --force {{item}}"
  with_items:
  - phpdoc/phpDocumentor
  - phpunit/PHPUnit
  - phing/phing
  ignore_errors: yes

- name: Configure PHP Oauth
  copy: src=oauth.ini dest=/etc/php5/mods-available owner=root mode=0755

- name: Link PHP Oauth to PHP SAPIs
  file: src=../../mods-available/oauth.ini path=/etc/php5/{{item}}/conf.d/20-oauth.ini state=link
  with_items:
  - apache2
  - cli
  ignore_errors: yes

- name: Configure XDebug
  copy: src=xdebug.ini dest=/etc/php5/mods-available owner=root mode=0755

- name: Link XDebug to PHP SAPIs
  file: src=../../mods-available/xdebug.ini path=/etc/php5/{{item}}/conf.d/05-xdebug.ini state=link
  with_items:
  - apache2
  - cli
  ignore_errors: yes

- name: Configure PHP Memcache
  copy: src=memcache.ini dest=/etc/php5/mods-available owner=root mode=0755

- name: Link Memcache to PHP SAPIs
  file: src=../../mods-available/memcache.ini path=/etc/php5/{{item}}/conf.d/20-memcache.ini state=link
  with_items:
  - apache2
  - cli
  ignore_errors: yes

- name: Install Composer
  shell: "{{item}}"
  with_items:
   - curl -sS https://getcomposer.org/installer | php
   - mv composer.phar /usr/local/bin/composer

- name: Install CodeCeption
  shell: "{{item}}"
  with_items:
   - wget http://codeception.com/codecept.phar
   - mv codecept.phar /usr/local/bin/codecept

- name: Add Postfix setting to Set Selections
  command: debconf-set-selections <<< "{{item}}"
  with_items:
  - postfix postfix/mailname string sandbox.creatingit.co.uk
  - postfix postfix/main_mailer_type string 'Internet Site'

- name: Install Postfix
  apt: pkg=postfix state=latest

- name: Start Memcached
  service: name=memcached state=restarted enabled=yes

- name: Start Apache
  service: name=apache2 state=restarted enabled=yes

- name: Create Locate DB
  command: updatedb