#!/bin/bash

# this script is used to attach a site to the current apache installation
if [ -z "$1" ]
then
	echo "You must define a project to detach"
	exit 1
fi

echo "Detaching site $1"

a2dissite $1 > /dev/null

service apache2 restart

unlink /etc/apache2/sites-available/$1.conf



if [ -d ~/workspace/$1 ]
then
    read -r -p "Backup the database? [y|N] " response
    if [[ $response =~ ^[Yy]$ ]]
    then
        echo "Backing up SQL database"
        mkdir -p ~/workspace/$1/assets/db/
        mysqldump --opt -c --max_allowed_packet=512M --add-drop-database --add-drop-table --dump-date --databases $1 > ~/workspace/$1/assets/db/sandbox.sql
        echo " > ~/workspace/$1/assets/db/sandbox.sql"
    fi
fi
